#!/usr/bin/python
#Created by Cody Skinner

import requests
import json
import sys
import ConfigParser
import argparse

#Parser for command line arguments
parser = argparse.ArgumentParser(description="Check status of a World of Warcraft realm")
parser.add_argument("realm", help="Get information on this realm")
parser.add_argument("-b", "--battlegroup", help="Realm battlegroup", action="store_true")
parser.add_argument("-c", "--connected", help="Connected realms", action="store_true")
parser.add_argument("-p", "--population", help="Realm population", action="store_true")
parser.add_argument("-s", "--status", help="Online status", action="store_true")
parser.add_argument("-t", "--type", help="Realm type", action="store_true")
parser.add_argument("-z", "--timezone", help="Realm Timezone", action="store_true")
args = parser.parse_args()

#Parser for config file
config = ConfigParser.ConfigParser()
config.read("config.py")
apikey = config.get('BAPI', 'apikey')
url = "https://us.api.battle.net/wow/realm/status?local=en_US&apikey="+apikey+"&realms="+args.realm

#API requests
response = requests.get(url)
data = response.json()

#Main loop
if args.battlegroup == 1:
    print data['realms'][0]['name']+ "'s battlegroup is: " + data['realms'][0]['battlegroup']
if args.connected == 1:
    print data['realms'][0]['name'] + " is connected to: " + str(data['realms'][0]['connected_realms'])
if args.population == 1:
    print data['realms'][0]['name'] + "'s population is " + data['realms'][0]['population']
if args.status == 1:
    if data['realms'][0]['status'] == 1:
        print data['realms'][0]['name'] + " is online!"
    else:
        print data['realms'][0]['name'] + " is offline"
if args.type == 1:
    print data['realms'][0]['name'] + " is a " + data['realms'][0]['type'] + " realm."
if args.timezone == 1:
    print data['realms'][0]['name'] + "'s timezone is " + data['realms'][0]['timezone']
