#!/usr/bin/python
#Created by Cody Skinner

import requests
import json
import sys
import ConfigParser

# Check for more less than 2 args, then check for -h, then check for less than 3
# Look at using ArgumentParser to clean up the flag checking
if len(sys.argv) < 2:
    print("Please provide arguments\nRealmCheck.py [realm_name] [flag]\nRealmCheck.py -h for help")
    exit()

if sys.argv[1] == '-h':
        print("Usage:\nRealmCheck [realm_name] [flag]")
        print("-h for help (this text)")
        print("-s for online status")
        print("-t for realm type")
        print("-c for connected realms")
        print("-z for realm timezone")
        print("-p for realm population")
        print("-b for battlegroup")
        exit()

if len(sys.argv) < 3:
    print("Please provide arguments\nRealmCheck.py [realm_name] [flag]\n'RealmCheck.py -h' for help")
    exit()
if sys.argv[1] == '-h':
    print("Usage:\nRealmCheck.py [realm_name] [flag]")
    print("-h for help (this text)")
    print("-s for online status")
    print("-t for realm type")
    print("-c for connected realms")
    print("-z for realm timezone")
    print("-p for realm population")
    print("-b for battlegroup")
    exit()

realm = sys.argv[1]
flag = sys.argv[2]

#Use the following to use a config.ini file for apikey and url
config = ConfigParser.ConfigParser()
config.read("config.py")
apikey = config.get('BAPI', 'apikey')
url = "https://us.api.battle.net/wow/realm/status?local=en_US&apikey="+apikey+"&realms="+realm

response = requests.get(url)
data = response.json()

if flag == '-s':
    if data['realms'][0]['status'] == 1:
        print data['realms'][0]['name'] + " is online!"
    elif data['realms'][0]['status'] == 0:
        print data['realms'][0]['name'] + " is offline :("
    exit()
if flag == '-t':
    print data['realms'][0]['name'] + " is a " + data['realms'][0]['type'] + " realm."
    exit()
if flag == '-c':
    print data['realms'][0]['name'] + " is connected to the following realms:" + str(data['realms'][0]['connected_realms'])
    exit()
if flag == '-z':
    print data['realms'][0]['name'] + "'s timezone is set to: " + data['realms'][0]['timezone']
    exit()
if flag == '-p':
    print "Population on " + data['realms'][0]['name'] + " is " + data['realms'][0]['population']
    exit()
if flag == '-b':
    print data['realms'][0]['name'] + "'s battlegroup is: " + data['realms'][0]['battlegroup']
    exit()
else:
    print("Invalid option, please try again. Use 'RealmCheck -h' for help")
    exit()

